"""empty message

Revision ID: 809a78be2c40
Revises: 
Create Date: 2023-05-01 10:13:24.300735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '809a78be2c40'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('_password_hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('winelabels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('style', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_winelabels_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('grapes', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('story', sa.String(), nullable=True),
    sa.Column('label_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['label_id'], ['winelabels.id'], name=op.f('fk_wines_label_id_winelabels')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_wines_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wines')
    op.drop_table('winelabels')
    op.drop_table('users')
    # ### end Alembic commands ###
